/* This file is provided by the meta-mender layer. */

#ifndef HEADER_CONFIG_MENDER_DEFINES_H
#define HEADER_CONFIG_MENDER_DEFINES_H

/* Shell variables */
#define MENDER_BOOT_PART_NUMBER 0
#define MENDER_BOOT_PART_NUMBER_HEX 0
#define MENDER_ROOTFS_PART_A_NUMBER 1
#define MENDER_ROOTFS_PART_A_NUMBER_HEX 1
#define MENDER_ROOTFS_PART_B_NUMBER 2
#define MENDER_ROOTFS_PART_B_NUMBER_HEX 2
#define MENDER_UBOOT_STORAGE_INTERFACE "mmc"
#define MENDER_UBOOT_STORAGE_DEVICE 0
#define MENDER_UBOOT_CONFIG_SYS_MMC_ENV_PART 0

/* BB variables. */
#define MENDER_STORAGE_DEVICE "mmcblk1"
#define MENDER_STORAGE_DEVICE_BASE "mmcblk1p"
#define MENDER_UBOOT_ENV_STORAGE_DEVICE_OFFSET_1 0x100000
#define MENDER_UBOOT_ENV_STORAGE_DEVICE_OFFSET_2 0x180000
#define MENDER_ROOTFS_PART_A_NAME "/dev/mmcblk1p1"
#define MENDER_ROOTFS_PART_B_NAME "/dev/mmcblk1p2"

/* For sanity checks. */
#define MENDER_BOOTENV_SIZE 0x2000

#define MENDER_BOOT_KERNEL_TYPE "bootm"
#define MENDER_KERNEL_NAME "uImage"
#define MENDER_DTB_NAME "imx6dl-ts7970-revf.dtb"
#define MENDER_UBOOT_PRE_SETUP_COMMANDS ""
#define MENDER_UBOOT_POST_SETUP_COMMANDS ""
#endif /* !HEADER_CONFIG_MENDER_DEFINES_H */